// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbAGxTeuyOfhhJm5W4zaVNU8xCAxeDTMc',
    appId: '1:271109763919:web:22fbc320a42a5e07d4cb3a',
    messagingSenderId: '271109763919',
    projectId: 'project-login-6eb35',
    authDomain: 'project-login-6eb35.firebaseapp.com',
    storageBucket: 'project-login-6eb35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDu0wQud9lnNySmyW_eF36IUumQ3msAA',
    appId: '1:271109763919:android:86dd26165e2bc711d4cb3a',
    messagingSenderId: '271109763919',
    projectId: 'project-login-6eb35',
    storageBucket: 'project-login-6eb35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5kbEuBBVuMxQkFB2_zR-ClSZ6PLAAIA',
    appId: '1:271109763919:ios:de0fdfecc6eba59bd4cb3a',
    messagingSenderId: '271109763919',
    projectId: 'project-login-6eb35',
    storageBucket: 'project-login-6eb35.appspot.com',
    iosClientId: '271109763919-08ed0k59t2qvvjmkrb1sit2f13691jtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5kbEuBBVuMxQkFB2_zR-ClSZ6PLAAIA',
    appId: '1:271109763919:ios:de0fdfecc6eba59bd4cb3a',
    messagingSenderId: '271109763919',
    projectId: 'project-login-6eb35',
    storageBucket: 'project-login-6eb35.appspot.com',
    iosClientId: '271109763919-08ed0k59t2qvvjmkrb1sit2f13691jtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp22',
  );
}
